// autogenerated by sql-generate v0.3.0 on Thu Oct 23 2014 06:38:57 GMT-0700 (PDT)
// note probably won't use this - moving to Bookshelf

var sql = require('sql');


/**
 * SQL definition for public.attestations
 */
exports.attestations = sql.define({
  name: 'attestations',
  columns: [
    { name: 'ident' },
    { name: 'descr' },
    { name: 'trustgroup' }
  ]
});


/**
 * SQL definition for public.audit_history
 */
exports.audit_history = sql.define({
  name: 'audit_history',
  columns: [
    { name: 'member' },
    { name: 'what' },
    { name: 'entered' }
  ]
});


/**
 * SQL definition for public.languages
 */
exports.languages = sql.define({
  name: 'languages',
  columns: [
    { name: 'name' },
    { name: 'iso_639_1' }
  ]
});


/**
 * SQL definition for public.language_skill
 */
exports.language_skill = sql.define({
  name: 'language_skill',
  columns: [
    { name: 'skill' },
    { name: 'seq' }
  ]
});


/**
 * SQL definition for public.mailinglist
 */
exports.mailinglist = sql.define({
  name: 'mailinglist',
  columns: [
    { name: 'lhs' },
    { name: 'trustgroup' },
    { name: 'descr' },
    { name: 'members_only' },
    { name: 'can_add_self' },
    { name: 'automatic' },
    { name: 'always_crypt' },
    { name: 'virtual' },
    { name: 'activity' },
    { name: 'email_footer' },
    { name: 'pubkey' },
    { name: 'key_update_at' },
    { name: 'seckey' }
  ]
});


/**
 * SQL definition for public.member
 */
exports.member = sql.define({
  name: 'member',
  columns: [
    { name: 'ident' },
    { name: 'descr' },
    { name: 'affiliation' },
    { name: 'password' },
    { name: 'passwd_chat' },
    { name: 'tz_info' },
    { name: 'im_info' },
    { name: 'tel_info' },
    { name: 'sms_info' },
    { name: 'post_info' },
    { name: 'bio_info' },
    { name: 'airport' },
    { name: 'no_email' },
    { name: 'hide_email' },
    { name: 'furlough' },
    { name: 'change_pw' },
    { name: 'entered' },
    { name: 'activity' },
    { name: 'uuid' },
    { name: 'sysadmin' },
    { name: 'login_attempts' },
    { name: 'login_try_begin' },
    { name: 'image' }
  ]
});


/**
 * SQL definition for public.member_details
 */
exports.member_details = sql.define({
  name: 'member_details',
  columns: [
    { name: 'member' },
    { name: 'type' },
    { name: 'entered' },
    { name: 'value' }
  ]
});


/**
 * SQL definition for public.member_detail_types
 */
exports.member_detail_types = sql.define({
  name: 'member_detail_types',
  columns: [
    { name: 'type' },
    { name: 'display_name' }
  ]
});


/**
 * SQL definition for public.member_email
 */
exports.member_email = sql.define({
  name: 'member_email',
  columns: [
    { name: 'member' },
    { name: 'email' },
    { name: 'pgpkey_id' },
    { name: 'verified' },
    { name: 'pgpkey_expire' },
    { name: 'keyring' },
    { name: 'keyring_update_at' }
  ]
});


/**
 * SQL definition for public.member_language_skill
 */
exports.member_language_skill = sql.define({
  name: 'member_language_skill',
  columns: [
    { name: 'member' },
    { name: 'language' },
    { name: 'skill' },
    { name: 'entered' }
  ]
});


/**
 * SQL definition for public.member_mailinglist
 */
exports.member_mailinglist = sql.define({
  name: 'member_mailinglist',
  columns: [
    { name: 'member' },
    { name: 'lhs' },
    { name: 'trustgroup' },
    { name: 'virtual' }
  ]
});


/**
 * SQL definition for public.member_state
 */
exports.member_state = sql.define({
  name: 'member_state',
  columns: [
    { name: 'ident' },
    { name: 'can_login' },
    { name: 'can_see' },
    { name: 'can_send' },
    { name: 'can_recv' },
    { name: 'blocked' },
    { name: 'hidden' }
  ]
});


/**
 * SQL definition for public.member_trustgroup
 */
exports.member_trustgroup = sql.define({
  name: 'member_trustgroup',
  columns: [
    { name: 'member' },
    { name: 'trustgroup' },
    { name: 'admin' },
    { name: 'entered' },
    { name: 'activity' },
    { name: 'state' },
    { name: 'email' }
  ]
});


/**
 * SQL definition for public.member_vouch
 */
exports.member_vouch = sql.define({
  name: 'member_vouch',
  columns: [
    { name: 'vouchor' },
    { name: 'vouchee' },
    { name: 'trustgroup' },
    { name: 'comment' },
    { name: 'entered' },
    { name: 'positive' }
  ]
});


/**
 * SQL definition for public.message_catalog
 */
exports.message_catalog = sql.define({
  name: 'message_catalog',
  columns: [
    { name: 'trustgroup' },
    { name: 'message_type' },
    { name: 'message_template' }
  ]
});


/**
 * SQL definition for public.message_types
 */
exports.message_types = sql.define({
  name: 'message_types',
  columns: [
    { name: 'ident' },
    { name: 'descr' }
  ]
});


/**
 * SQL definition for public.openid_associations
 */
exports.openid_associations = sql.define({
  name: 'openid_associations',
  columns: [
    { name: 'uuid' },
    { name: 'assoc_type' },
    { name: 'session_type' },
    { name: 'mac_key' },
    { name: 'timestamp' }
  ]
});


/**
 * SQL definition for public.openid_source_cache
 */
exports.openid_source_cache = sql.define({
  name: 'openid_source_cache',
  columns: [
    { name: 'src_ip' },
    { name: 'last_try' },
    { name: 'attempt_count' }
  ]
});


/**
 * SQL definition for public.second_factors
 * second_factor belongs to member
 * member is foreign key for member.ident
 * member has many second_factors
 * type is a foreign key
 * second_factor belongs to SecondFactorType
 */
exports.second_factors = sql.define({
  name: 'second_factors',
  columns: [
    { name: 'uuid' },
    { name: 'member' },
    { name: 'type' },
    { name: 'entered' },
    { name: 'active' },
    { name: 'counter' },
    { name: 'key' },
    { name: 'descr' }
  ]
});


/**
 * SQL definition for public.second_factor_types
 */
exports.second_factor_types = sql.define({
  name: 'second_factor_types',
  columns: [
    { name: 'type' },
    { name: 'descr' }
  ]
});


/**
 * SQL definition for public.trustgroup
 */
exports.trustgroup = sql.define({
  name: 'trustgroup',
  columns: [
    { name: 'ident' },
    { name: 'descr' },
    { name: 'shortname' },
    { name: 'min_invouch' },
    { name: 'target_invouch' },
    { name: 'pgp_required' },
    { name: 'please_vouch' },
    { name: 'vouch_adminonly' },
    { name: 'nom_enabled' },
    { name: 'min_outvouch' },
    { name: 'max_inactivity' },
    { name: 'can_time_out' },
    { name: 'max_vouchdays' },
    { name: 'idle_guard' },
    { name: 'has_wiki' }
  ]
});


/**
 * SQL definition for public.web_sessions
 */
exports.web_sessions = sql.define({
  name: 'web_sessions',
  columns: [
    { name: 'id' },
    { name: 'a_session' }
  ]
});


